"use client";

import Image from "next/image";
import Link from "next/link";
import { Minus, Plus, Trash2 } from "lucide-react";
import { CheckoutButton } from "@/components/cart-actions";
import { useCart } from "@/components/cart-provider";
import { formatPrice, getEffectivePrice } from "@/lib/commerce";

export function CartPage() {
  const { items, subtotal, removeItem, updateQuantity } = useCart();
  if (!items.length) return <div className="rounded-2xl border border-dashed border-slate-300 bg-white p-10 text-center"><h1 className="text-2xl font-black text-slate-950">Your cart is empty.</h1><p className="mt-2 text-slate-600">Add an in-stock product with a confirmed online price to check out securely.</p><Link href="/shop" className="mt-6 inline-flex rounded-lg bg-slate-950 px-5 py-3 text-sm font-black text-white">Continue shopping</Link></div>;
  return <div className="grid gap-8 lg:grid-cols-[1fr_22rem]"><div className="overflow-hidden rounded-2xl border border-slate-200 bg-white">{items.map((item) => { const price = getEffectivePrice(item.product); return <article key={item.product.id} className="flex gap-4 border-b border-slate-100 p-4 last:border-0 sm:p-5"><div className="relative size-20 shrink-0 overflow-hidden rounded-lg bg-slate-100"><Image src={item.product.image || "/placeholders/smartphone.webp"} alt="" fill sizes="80px" className="object-cover" /></div><div className="min-w-0 flex-1"><p className="text-xs font-black uppercase tracking-wide text-cyan-700">{item.product.brand}</p><Link href={`/shop/${item.product.slug}`} className="mt-1 block font-black text-slate-950 hover:text-cyan-700">{item.product.title}</Link><p className="mt-1 text-sm font-bold text-slate-950">{price !== null ? formatPrice(price, item.product.currency) : "Price confirmed at checkout"}</p><div className="mt-3 flex flex-wrap items-center gap-3"><div className="inline-flex items-center rounded-lg border border-slate-200"><button type="button" aria-label={`Reduce ${item.product.title} quantity`} onClick={() => updateQuantity(item.product.id, item.quantity - 1)} className="p-2"><Minus className="size-4" /></button><span className="min-w-8 text-center text-sm font-bold">{item.quantity}</span><button type="button" aria-label={`Increase ${item.product.title} quantity`} onClick={() => updateQuantity(item.product.id, item.quantity + 1)} className="p-2"><Plus className="size-4" /></button></div><button type="button" onClick={() => removeItem(item.product.id)} className="inline-flex items-center gap-1 text-xs font-bold text-slate-500 hover:text-red-700"><Trash2 className="size-3.5" />Remove</button></div></div><p className="text-sm font-black text-slate-950">{price !== null ? formatPrice(price * item.quantity, item.product.currency) : ""}</p></article>; })}</div><aside className="h-fit rounded-2xl bg-slate-950 p-6 text-white"><h2 className="text-lg font-black">Order summary</h2><div className="mt-5 flex items-center justify-between border-y border-white/10 py-4"><span className="text-sm text-slate-300">Subtotal</span><span className="text-lg font-black">{formatPrice(subtotal)}</span></div><p className="mt-4 text-xs leading-5 text-slate-400">Secure payment is handled by Stripe. Delivery or collection is confirmed by DL Gadgets after payment.</p><div className="mt-5"><CheckoutButton /></div></aside></div>;
}
