"use client";

import { useMemo, useState } from "react";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { EmptyState, ProductGrid } from "@/components/store";
import { getEffectivePrice } from "@/lib/commerce";
import type { Category, Product } from "@/types";

export function ShopExperience({ products, categories, initialQuery = "" }: { products: Product[]; categories: Category[]; initialQuery?: string }) {
  const [query, setQuery] = useState(initialQuery); const [category, setCategory] = useState(""); const [brand, setBrand] = useState(""); const [condition, setCondition] = useState(""); const [priceType, setPriceType] = useState("all"); const [inStock, setInStock] = useState(false); const [sort, setSort] = useState("featured");
  const brands = useMemo(() => [...new Set(products.map((product) => product.brand))].sort(), [products]); const conditions = useMemo(() => [...new Set(products.map((product) => product.condition))], [products]);
  const filtered = useMemo(() => products.filter((product) => { const haystack = `${product.title} ${product.brand} ${product.category} ${product.tags?.join(" ") || ""}`.toLowerCase(); const hasPrice = getEffectivePrice(product) !== null && !product.requestPrice; return (!query || haystack.includes(query.toLowerCase())) && (!category || product.category === category) && (!brand || product.brand === brand) && (!condition || product.condition === condition) && (priceType === "all" || (priceType === "priced" ? hasPrice : product.requestPrice)) && (!inStock || (product.inStock && product.quantity !== 0)); }).sort((a, b) => { if (sort === "name") return a.title.localeCompare(b.title); if (sort === "price-low") return (getEffectivePrice(a) ?? Number.MAX_SAFE_INTEGER) - (getEffectivePrice(b) ?? Number.MAX_SAFE_INTEGER); if (sort === "price-high") return (getEffectivePrice(b) ?? -1) - (getEffectivePrice(a) ?? -1); return Number(b.featured) - Number(a.featured); }), [products, query, category, brand, condition, priceType, inStock, sort]);
  const reset = () => { setQuery(""); setCategory(""); setBrand(""); setCondition(""); setPriceType("all"); setInStock(false); setSort("featured"); };
  const active = query || category || brand || condition || priceType !== "all" || inStock || sort !== "featured";
  return <div><div className="rounded-xl border border-slate-200 bg-slate-50 p-4"><div className="grid gap-3 lg:grid-cols-[1.4fr_1fr_1fr]"><label className="relative"><span className="sr-only">Search products</span><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products, brands or models" className="w-full rounded-lg border border-slate-300 bg-white py-3 pl-10 pr-3 text-sm outline-none focus:border-cyan-500" /></label><Select label="Category" value={category} setValue={setCategory} options={categories.map((item) => item.title)} /><Select label="Brand" value={brand} setValue={setBrand} options={brands} /></div><div className="mt-3 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><Select label="Condition" value={condition} setValue={setCondition} options={conditions} /><label><span className="sr-only">Filter by price type</span><select value={priceType} onChange={(event) => setPriceType(event.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-3 text-sm font-semibold outline-none focus:border-cyan-500"><option value="all">All pricing</option><option value="priced">Online price</option><option value="request">Request price</option></select></label><label className="flex items-center gap-3 rounded-lg border border-slate-300 bg-white px-3 py-3 text-sm font-semibold text-slate-700"><input type="checkbox" checked={inStock} onChange={(event) => setInStock(event.target.checked)} className="size-4 accent-cyan-600" />In stock only</label><label className="relative"><span className="sr-only">Sort products</span><select value={sort} onChange={(event) => setSort(event.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-3 text-sm font-semibold outline-none focus:border-cyan-500"><option value="featured">Sort: Featured</option><option value="name">Sort: Name A-Z</option><option value="price-low">Price: low to high</option><option value="price-high">Price: high to low</option></select><SlidersHorizontal className="pointer-events-none absolute right-3 top-3.5 size-4 text-slate-400" /></label></div></div><div className="mb-5 mt-6 flex items-center justify-between"><p className="text-sm text-slate-600"><span className="font-black text-slate-950">{filtered.length}</span> products</p>{active && <button onClick={reset} className="inline-flex items-center gap-1 text-sm font-bold text-cyan-700"><X className="size-4" />Reset filters</button>}</div>{filtered.length ? <ProductGrid products={filtered} /> : <EmptyState />}</div>;
}
function Select({ label, value, setValue, options }: { label: string; value: string; setValue: (value: string) => void; options: string[] }) { const allLabel = label === "Category" ? "All categories" : `All ${label.toLowerCase()}s`; return <label><span className="sr-only">Filter by {label}</span><select value={value} onChange={(event) => setValue(event.target.value)} className="w-full rounded-lg border border-slate-300 bg-white px-3 py-3 text-sm font-semibold outline-none focus:border-cyan-500"><option value="">{allLabel}</option>{options.map((item) => <option key={item} value={item}>{item}</option>)}</select></label>; }
