"use client";

import { useMemo, useState } from "react";
import { Search, SlidersHorizontal, X } from "lucide-react";
import { EmptyState, ProductGrid } from "@/components/store";
import type { Category, Product } from "@/types";

export function ProductSearch({ value, onChange }: { value: string; onChange: (value: string) => void }) { return <label className="relative block"><span className="sr-only">Search products</span><Search className="absolute left-4 top-1/2 size-5 -translate-y-1/2 text-slate-400" /><input value={value} onChange={(event) => onChange(event.target.value)} placeholder="Search by product, brand, or model" className="w-full rounded-xl border border-slate-200 bg-white py-3.5 pl-11 pr-4 text-sm text-slate-950 outline-none transition placeholder:text-slate-400 focus:border-cyan-500 focus:ring-4 focus:ring-cyan-100" /></label>; }

export function ProductFilters({ categories, brands, category, setCategory, brand, setBrand }: { categories: Category[]; brands: string[]; category: string; setCategory: (value: string) => void; brand: string; setBrand: (value: string) => void }) { return <div className="flex flex-col gap-3 sm:flex-row"><label className="relative flex-1"><span className="sr-only">Filter by category</span><select value={category} onChange={(event) => setCategory(event.target.value)} className="w-full appearance-none rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 outline-none focus:border-cyan-500"><option value="">All categories</option>{categories.map((item) => <option key={item.slug} value={item.title}>{item.title}</option>)}</select><SlidersHorizontal className="pointer-events-none absolute right-4 top-3.5 size-4 text-slate-400" /></label><label className="flex-1"><span className="sr-only">Filter by brand</span><select value={brand} onChange={(event) => setBrand(event.target.value)} className="w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-semibold text-slate-700 outline-none focus:border-cyan-500"><option value="">All brands</option>{brands.map((item) => <option key={item}>{item}</option>)}</select></label></div>; }

export function ShopExperience({ products, categories, initialQuery = "" }: { products: Product[]; categories: Category[]; initialQuery?: string }) { const [query, setQuery] = useState(initialQuery); const [category, setCategory] = useState(""); const [brand, setBrand] = useState(""); const brands = useMemo(() => [...new Set(products.map((product) => product.brand))].sort(), [products]); const filtered = useMemo(() => products.filter((product) => { const haystack = `${product.title} ${product.brand} ${product.category}`.toLowerCase(); return (!query || haystack.includes(query.toLowerCase())) && (!category || product.category === category) && (!brand || product.brand === brand); }), [products, query, category, brand]); const reset = () => { setQuery(""); setCategory(""); setBrand(""); }; return <div><div className="rounded-2xl border border-slate-200 bg-slate-50 p-4 sm:p-5"><div className="grid gap-3 lg:grid-cols-[1.15fr_1fr]"><ProductSearch value={query} onChange={setQuery} /><ProductFilters categories={categories} brands={brands} category={category} setCategory={setCategory} brand={brand} setBrand={setBrand} /></div></div><div className="mb-6 mt-7 flex items-center justify-between"><p className="text-sm text-slate-500"><span className="font-bold text-slate-950">{filtered.length}</span> {filtered.length === 1 ? "product" : "products"} available to enquire about</p>{(query || category || brand) && <button onClick={reset} className="inline-flex items-center gap-1 text-sm font-bold text-cyan-700 hover:text-cyan-950"><X className="size-4" />Clear filters</button>}</div>{filtered.length ? <ProductGrid products={filtered} /> : <EmptyState />}</div>; }
