"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { Menu, Search, X, Zap } from "lucide-react";
import { Container } from "@/components/store";

const links = [{ href: "/", label: "Home" }, { href: "/shop", label: "Shop" }, { href: "/category/smartphones", label: "Smartphones" }, { href: "/category/tablets", label: "Tablets" }, { href: "/category/gaming-devices", label: "Gaming" }, { href: "/category/security-cameras", label: "Security Cameras" }, { href: "/contact", label: "Contact" }];
export function Brand({ compact = false }: { compact?: boolean }) { return <Link href="/" className="flex shrink-0 items-center gap-2.5" aria-label="DL Gadgets home"><span className="grid size-9 place-items-center rounded-lg bg-gradient-to-br from-cyan-300 to-emerald-400 text-slate-950"><Zap className="size-5 fill-current" /></span><span><span className="block text-base font-black tracking-tight text-white">DL<span className="text-cyan-300">GADGETS</span></span>{!compact && <span className="block text-[8px] font-bold uppercase tracking-[.17em] text-slate-400">Your Tech Revolution</span>}</span></Link>; }
export function SiteHeader() { const pathname = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const search = (event: FormEvent) => { event.preventDefault(); router.push(`/shop?q=${encodeURIComponent(query)}`); setOpen(false); }; return <header className="sticky top-0 z-50"><div className="bg-cyan-500 text-slate-950"><Container className="flex h-8 items-center justify-center text-[11px] font-bold sm:justify-between"><span>Malta-based support · Quality checked electronics</span><span className="hidden sm:block">Request before payment · Collection or delivery</span></Container></div><div className="border-b border-white/10 bg-slate-950"><Container className="flex h-16 items-center gap-4"><Brand /><form onSubmit={search} className="hidden max-w-xl flex-1 lg:block"><label className="sr-only" htmlFor="site-search">Search products</label><div className="relative"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input id="site-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search phones, tablets, gaming and more" className="w-full rounded-lg border border-white/10 bg-white/5 py-2.5 pl-10 pr-3 text-sm text-white outline-none placeholder:text-slate-400 focus:border-cyan-300" /></div></form><Link href="/request-order" className="ml-auto hidden rounded-lg bg-white px-4 py-2.5 text-xs font-black text-slate-950 transition hover:bg-cyan-200 sm:inline-flex">Request order</Link><button aria-label={open ? "Close menu" : "Open menu"} onClick={() => setOpen(!open)} className="rounded-lg p-2 text-white lg:hidden">{open ? <X /> : <Menu />}</button></Container></div><div className="hidden border-b border-slate-200 bg-white lg:block"><Container><nav className="flex items-center gap-6 overflow-x-auto py-3">{links.map((link) => <Link key={link.href} href={link.href} className={`whitespace-nowrap text-sm font-bold ${pathname === link.href ? "text-cyan-700" : "text-slate-700 hover:text-cyan-700"}`}>{link.label}</Link>)}</nav></Container></div>{open && <MobileMenu close={() => setOpen(false)} query={query} setQuery={setQuery} search={search} />}</header>; }
function MobileMenu({ close, query, setQuery, search }: { close: () => void; query: string; setQuery: (value: string) => void; search: (event: FormEvent) => void }) { return <div className="border-b border-slate-200 bg-white shadow-lg lg:hidden"><Container className="py-4"><form onSubmit={search}><label className="sr-only" htmlFor="mobile-search">Search products</label><input id="mobile-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products" className="w-full rounded-lg border border-slate-300 px-4 py-3 text-sm outline-none focus:border-cyan-500" /></form><nav className="mt-3 grid grid-cols-2 gap-1">{links.map((link) => <Link onClick={close} key={link.href} href={link.href} className="rounded-lg px-3 py-3 text-sm font-bold text-slate-800 hover:bg-slate-100">{link.label}</Link>)}<Link onClick={close} href="/request-order" className="col-span-2 mt-2 rounded-lg bg-slate-950 px-3 py-3 text-center text-sm font-black text-white">Request an order</Link></nav></Container></div>; }
