"use client";

import Link from "next/link";
import { usePathname, useRouter } from "next/navigation";
import { FormEvent, useState } from "react";
import { Menu, Search, X, Zap } from "lucide-react";
import { Container } from "@/components/store";

const links = [{ href: "/shop", label: "Shop" }, { href: "/category/smartphones", label: "Categories" }, { href: "/about", label: "About" }, { href: "/contact", label: "Contact" }];

export function Brand() { return <Link href="/" className="flex items-center gap-2.5" aria-label="DL Gadgets home"><span className="grid size-9 place-items-center rounded-xl bg-gradient-to-br from-cyan-300 via-cyan-500 to-emerald-400 text-slate-950 shadow-lg shadow-cyan-400/20"><Zap className="size-5 fill-current" /></span><span><span className="block text-base font-black tracking-tight text-white">DL<span className="text-cyan-300">GADGETS</span></span><span className="block text-[8px] font-bold uppercase tracking-[.18em] text-slate-400">Your Tech Revolution</span></span></Link>; }

export function SiteHeader() { const pathname = usePathname(); const router = useRouter(); const [open, setOpen] = useState(false); const [query, setQuery] = useState(""); const search = (event: FormEvent) => { event.preventDefault(); router.push(`/shop?q=${encodeURIComponent(query)}`); setOpen(false); }; return <header className="sticky top-0 z-50 border-b border-white/10 bg-slate-950/95 backdrop-blur"><Container className="flex h-18 items-center justify-between gap-4"><Brand /><nav className="hidden items-center gap-6 lg:flex">{links.map((link) => <Link key={link.href} href={link.href} className={`text-sm font-bold transition ${pathname === link.href || (link.label === "Categories" && pathname.startsWith("/category")) ? "text-cyan-300" : "text-slate-300 hover:text-white"}`}>{link.label}</Link>)}</nav><form onSubmit={search} className="hidden max-w-xs flex-1 lg:flex"><label className="sr-only" htmlFor="site-search">Search products</label><div className="relative w-full"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" /><input id="site-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products" className="w-full rounded-lg border border-white/10 bg-white/5 py-2 pl-9 pr-3 text-sm text-white outline-none placeholder:text-slate-500 focus:border-cyan-300" /></div></form><Link href="/request-order" className="hidden rounded-lg bg-cyan-300 px-4 py-2 text-xs font-black text-slate-950 transition hover:bg-cyan-200 sm:inline-flex">Request order</Link><button aria-label={open ? "Close menu" : "Open menu"} onClick={() => setOpen(!open)} className="rounded-lg p-2 text-white lg:hidden">{open ? <X /> : <Menu />}</button></Container>{open && <MobileMenu close={() => setOpen(false)} search={search} query={query} setQuery={setQuery} />}</header>; }

export function MobileMenu({ close, search, query, setQuery }: { close: () => void; search: (event: FormEvent) => void; query: string; setQuery: (value: string) => void }) { return <div className="border-t border-white/10 bg-slate-950 lg:hidden"><Container className="py-5"><form onSubmit={search}><label className="sr-only" htmlFor="mobile-search">Search products</label><input id="mobile-search" value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search products" className="w-full rounded-lg border border-white/10 bg-white/5 px-4 py-3 text-sm text-white outline-none focus:border-cyan-300" /></form><nav className="mt-4 grid gap-1">{links.map((link) => <Link onClick={close} key={link.href} href={link.href} className="rounded-lg px-3 py-3 text-sm font-bold text-slate-200 hover:bg-white/5">{link.label}</Link>)}<Link onClick={close} href="/request-order" className="mt-2 rounded-lg bg-cyan-300 px-3 py-3 text-center text-sm font-black text-slate-950">Request an order</Link></nav></Container></div>; }
