import Image from "next/image";
import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, BadgeCheck, Boxes, Camera, Check, ChevronRight, Gamepad2, Headphones, PackageCheck, ShieldCheck, Smartphone, Tablet, Truck, Wifi } from "lucide-react";
import type { Category, CategoryName, Product } from "@/types";
import { whatsappLink } from "@/lib/site";

const categoryArt: Record<CategoryName, { image: string; icon: typeof Smartphone }> = {
  Smartphones: { image: "/products/smartphone-studio.webp", icon: Smartphone }, Tablets: { image: "/placeholders/tablet.webp", icon: Tablet },
  "Gaming Devices": { image: "/placeholders/gaming.webp", icon: Gamepad2 }, "Security Cameras": { image: "/placeholders/security-camera.webp", icon: Camera },
  Accessories: { image: "/placeholders/accessory.webp", icon: Headphones }, "Smart Devices": { image: "/placeholders/accessory.webp", icon: Wifi },
  "Enterprise Devices": { image: "/placeholders/enterprise-device.webp", icon: Boxes }, "Clearance / Used Devices": { image: "/placeholders/smartphone.webp", icon: PackageCheck },
};

export function Container({ children, className = "" }: { children: ReactNode; className?: string }) { return <div className={`mx-auto w-full max-w-7xl px-4 sm:px-6 lg:px-8 ${className}`}>{children}</div>; }
export function Button({ href, children, variant = "primary", className = "" }: { href: string; children: ReactNode; variant?: "primary" | "secondary" | "dark"; className?: string }) { const styles = variant === "primary" ? "bg-cyan-500 text-slate-950 hover:bg-cyan-400" : variant === "dark" ? "bg-slate-950 text-white hover:bg-slate-800" : "border border-slate-300 bg-white text-slate-900 hover:border-cyan-500"; return <Link href={href} className={`inline-flex items-center justify-center gap-2 rounded-lg px-4 py-3 text-sm font-extrabold transition focus:outline-none focus:ring-2 focus:ring-cyan-500 ${styles} ${className}`}>{children}<ArrowRight className="size-4" /></Link>; }
export function SectionHeading({ eyebrow, title, children, action }: { eyebrow?: string; title: string; children?: ReactNode; action?: ReactNode }) { return <div className="mb-7 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-xs font-extrabold uppercase tracking-[.2em] text-cyan-700">{eyebrow}</p><h2 className="mt-2 text-2xl font-black tracking-tight text-slate-950 sm:text-3xl">{title}</h2>{children && <p className="mt-2 max-w-2xl text-sm leading-6 text-slate-600 sm:text-base">{children}</p>}</div>{action}</div>; }
export function Breadcrumb({ items }: { items: { label: string; href?: string }[] }) { return <nav aria-label="Breadcrumb" className="mb-5 flex flex-wrap items-center gap-2 text-sm text-slate-500">{items.map((item, index) => <span key={item.label} className="flex items-center gap-2">{index > 0 && <ChevronRight className="size-3" />}{item.href ? <Link href={item.href} className="hover:text-cyan-700">{item.label}</Link> : <span className="font-semibold text-slate-700">{item.label}</span>}</span>)}</nav>; }
export function ProductImage({ product, priority = false, className = "" }: { product: Product; priority?: boolean; className?: string }) { return <div className={`relative overflow-hidden bg-slate-100 ${className}`}><Image src={product.image || categoryArt[product.category].image} alt={`${product.title} product image`} fill sizes="(max-width: 640px) 50vw, (max-width: 1024px) 33vw, 25vw" priority={priority} className="object-cover transition duration-500 group-hover:scale-105" /></div>; }
export function CategoryCard({ category }: { category: Category }) { const art = categoryArt[category.title]; const Icon = art.icon; return <Link href={`/category/${category.slug}`} className="group relative isolate min-h-44 overflow-hidden rounded-xl bg-slate-950 p-5 text-white"><Image src={art.image} alt="" fill sizes="(max-width: 640px) 50vw, 25vw" className="-z-10 object-cover opacity-55 transition duration-500 group-hover:scale-105" /><div className="absolute inset-0 -z-10 bg-gradient-to-t from-slate-950 via-slate-950/45 to-slate-950/10" /><Icon className="size-6 text-cyan-300" /><h3 className="mt-12 text-lg font-black">{category.title}</h3><span className="mt-1 inline-flex items-center gap-1 text-sm font-bold text-cyan-200">Shop category <ChevronRight className="size-4" /></span></Link>; }
export function ProductCard({ product }: { product: Product }) { const stock = product.quantity ? `${product.quantity} in stock` : product.inStock ? "Enquire now" : "Check availability"; return <article className="group overflow-hidden rounded-xl border border-slate-200 bg-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-lg"><Link href={`/shop/${product.slug}`} className="block"><ProductImage product={product} className="aspect-square" /><div className="p-4"><div className="flex flex-wrap gap-2"><span className="text-xs font-extrabold uppercase tracking-wide text-cyan-700">{product.brand}</span><span className="text-xs text-slate-500">{product.category}</span></div><h3 className="mt-2 min-h-12 text-sm font-extrabold leading-5 text-slate-950 sm:text-base">{product.title}</h3><p className="mt-2 text-xs text-slate-500">{product.condition} · {stock}</p></div></Link><div className="flex items-center justify-between gap-2 border-t border-slate-100 px-4 py-3"><span className="text-sm font-black text-slate-950">Request price</span><Link href={`/request-order?product=${encodeURIComponent(product.title)}`} className="rounded-md bg-slate-950 px-3 py-2 text-xs font-bold text-white hover:bg-cyan-700">Request</Link></div></article>; }
export function ProductGrid({ products }: { products: Product[] }) { return <div className="grid grid-cols-2 gap-3 sm:gap-5 md:grid-cols-3 xl:grid-cols-4">{products.map((product) => <ProductCard key={product.id} product={product} />)}</div>; }
export function EmptyState({ title = "No products found", text = "Try a different search term or reset your filters." }: { title?: string; text?: string }) { return <div className="rounded-xl border border-dashed border-slate-300 bg-slate-50 p-10 text-center"><PackageCheck className="mx-auto size-9 text-cyan-700" /><h3 className="mt-3 font-black text-slate-950">{title}</h3><p className="mt-1 text-sm text-slate-500">{text}</p></div>; }
export function TrustBadges() { const items = [[ShieldCheck, "Malta-based support"], [BadgeCheck, "Quality checked"], [Truck, "Collection or delivery"], [Check, "Request before payment"]] as const; return <div className="grid divide-y divide-slate-200 rounded-xl border border-slate-200 bg-white sm:grid-cols-2 sm:divide-x sm:divide-y-0 lg:grid-cols-4">{items.map(([Icon, text]) => <div key={text} className="flex items-center gap-3 p-4"><Icon className="size-5 text-cyan-700" /><span className="text-sm font-bold text-slate-800">{text}</span></div>)}</div>; }
export function ContactCTA() { return <section className="rounded-2xl bg-slate-950 px-6 py-9 text-white sm:px-10"><div className="flex flex-col gap-5 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs font-bold uppercase tracking-[.2em] text-cyan-300">Need help choosing?</p><h2 className="mt-2 text-2xl font-black">Tell us what you need and we&apos;ll confirm the right option.</h2><p className="mt-2 text-sm text-slate-300">Ask about price, condition, availability, collection, or delivery anywhere in Malta.</p></div><Button href="/contact" variant="primary">Contact DL Gadgets</Button></div></section>; }
export function ProductDetail({ product }: { product: Product }) { const stock = product.quantity ? `${product.quantity} item${product.quantity === 1 ? "" : "s"} listed` : "Availability confirmed on request"; return <div className="grid gap-8 lg:grid-cols-[1fr_1fr]"><ProductImage product={product} priority className="aspect-square rounded-2xl border border-slate-200" /><div><div className="flex flex-wrap gap-2 text-xs font-bold"><span className="rounded-full bg-cyan-50 px-3 py-1 text-cyan-800">{product.category}</span><span className="rounded-full bg-slate-100 px-3 py-1 text-slate-600">{product.condition}</span></div><p className="mt-5 text-sm font-extrabold uppercase tracking-[.16em] text-cyan-700">{product.brand}</p><h1 className="mt-2 text-3xl font-black tracking-tight text-slate-950 sm:text-4xl">{product.title}</h1><p className="mt-4 leading-7 text-slate-600">{product.description || product.shortDescription}</p><dl className="mt-6 grid grid-cols-2 gap-3"><div className="rounded-lg bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Condition</dt><dd className="mt-1 font-bold text-slate-950">{product.condition}</dd></div><div className="rounded-lg bg-slate-50 p-4"><dt className="text-xs font-bold uppercase tracking-wide text-slate-500">Availability</dt><dd className="mt-1 font-bold text-slate-950">{stock}</dd></div></dl><div className="mt-7 flex flex-wrap gap-3"><Button href={`/request-order?product=${encodeURIComponent(product.title)}`}>Request order</Button><a href={whatsappLink(`Hello DL Gadgets, I would like to enquire about ${product.title}.`)} className="inline-flex items-center rounded-lg border border-slate-300 px-4 py-3 text-sm font-bold text-slate-800 hover:border-cyan-500">WhatsApp us</a></div><p className="mt-4 text-xs leading-5 text-slate-500">Final price, condition details, and availability are confirmed directly by DL Gadgets before payment.</p></div></div>; }
